### ISSUE TITLE
[FEATURE REQUEST] Glue packages from different sources

### ISSUE THREAD

**Issue by LevT2** [Devolutions/UniGetUI#1009]
I'd like having а unified look of the "identical" softwares coming from different sources.

There should be discussion here on what the term 'identical' mean. (package name? Version? etc,)

Personally, I'd like the possibility to mark a vast amount of the Winget or Scoop packages with matched descriptions coming from Chocolatey (as getting these descriptions is cheap).

**Comment by Mikey1993** [comment]
Yeah, sounds like a grouping option of similar packages is something that will be good for usability.
I think that at first the grouping should be done via the `Package Name`, as this should be identical cross sources in theory 99% of the times..

**Comment by marticliment** [comment]
Hello,

I have been looking at this issue, and Package Names are not identical in most of the cases. Therefore, there is no viable way to implement. 

P.D. source filtering and search options have eased the way in which packages can be found from different sources.
