### ISSUE TITLE
When does the update get pushed to scoop?

### ISSUE THREAD

**Issue by rp1231** [Devolutions/UniGetUI#112]
I see that v1.3 has been released,
But scoop is still showing v1.2 as the latest version.

When does the scoop version usually get updated?

**Comment by redactedscribe** [comment]
It's automatic but even so it can sometimes take up to a day or two for Scoop manifests to update. Longer if they've broken and someone needs to fix it. Usually it's within hours.

**Comment by redactedscribe** [comment]
`wingetui: Update to version 1.3.0` 9 minutes ago. Should be ready to download.

**Comment by martinet101** [comment]
Yes, and the winget one will come soon
