### ISSUE TITLE
[BUG] Winget creates many startup executions?

### ISSUE THREAD

**Issue by rumplin** [Devolutions/UniGetUI#1799]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Opening Task Manager in Windows 11, I see under the "Startup apps" section that Winget has around 100 entries.
Expanding the Winget app, I see repeating same command line commands.
Other apps have a single entry here.

Please see attached screenshots.

### Steps to reproduce the issue

1. Be in Windows 11
2. Open Task manager
3. go to tab "Startup apps"
4. Look at WingetUI
5. Observe more than one entry for WingetUI

### WingetUI Log

```text
N/A
```

### Package Managers Logs

```text
N/A
```

### Relevant information

I have been using WingetUI during most of it's versions. Could be that after every upgrade of Winget new entries get applied here?

### Screenshots and videos

![Screenshot 2024-02-18 101551](https://github.com/marticliment/WingetUI/assets/35449956/1e19c712-0412-46b2-8b64-a71b8bc507f9)
![Screenshot 2024-02-18 101808](https://github.com/marticliment/WingetUI/assets/35449956/b7a912dc-40b9-4f8d-8ead-ed48207eaa0e)
![Screenshot 2024-02-18 101827](https://github.com/marticliment/WingetUI/assets/35449956/ecf6e6a1-226b-458a-b2f9-8f9510962a57)

**Comment by marticliment** [comment]
Hello,

Task manager shows a tree of all the subprocess launched by WingetUI since it is launched (on login) until it is closed (at shutdown). Therefore, it looks as if all the process were ran at launch, but this is not true.

You can easily check this by running ProcessExplorer at startup and analyzing WingetUI's process tree.
