### ISSUE TITLE
[BUG] WingetUI will not launch. Says it requires the Windows App Runtime Version 1.5.

### ISSUE THREAD

**Issue by JeffIsTheCorn** [Devolutions/UniGetUI#2062]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I have been using WingetUI with no issue for a while now, but since the other day it won't launch. It pops up with an error message that says:
```
This application requires the Windows App Runtime
     Version 1.5
     (MSIX package version >= 5001.70.1338.0)

Do you want to install a compatible Windows App Runtime now?
```

I have clicked "Yes" and downloaded and installed the latest Windows App SDK, but it still will not launch.

### WingetUI Log

```text
I cannot access the logs because it will not launch.
```

### Package Managers Logs

```text
I cannot access the logs because it will not launch.
```

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/30010449/2f8aa19b-a5be-4f40-b67f-38dfad2ed36d)

**Comment by marticliment** [comment]
Please uninstall any "App Runtime", "Singleton" and "UI.Xaml" app from Windows Settings, and reinstall WingetUI

**Comment by JeffIsTheCorn** [comment]
I've uninstalled all of those apps and reinstalled WingetUI, but I am met with the same error on launch.

**Comment by marticliment** [comment]
Please downgrade WingetUI to the latest working version. I will try to fix this issue on the next version of WingetUI

**Comment by JeffIsTheCorn** [comment]
I've downgraded to 2.2.0 and it is running correctly.

**Comment by marticliment** [comment]
Hello,

I have set a detailed guide on how to reset all WingetUI dependencies. Please follow it if WingetUI is still not working:
[https://github.com/marticliment/WinGetUI/issues/2000](https://github.com/marticliment/WingetUI/issues/2000)

**Comment by marticliment** [comment]
Hello, everyone,

**WingetUI 3.0.2 has been published. It fixes**
 - Crashes with .NET Sdk 8.0.3 (no launch at all)
 - Crashes with .NET Sdk 8.0.4 (Cannot locate resource from 'ms-appx:///Microsoft.UI.Xaml/Themes/themeresources.xaml)
 - Crashes with the App Sdk (This app requires whe Windows App runtime) when it was already installed
 - Crashes when elevating WingetUI from non-admin users

**WingetUI 3.0.2 can be downloaded directly from [here](https://github.com/marticliment/WingetUI/releases/download/3.0.2/WingetUI.Installer.exe). If the crashes persist, please reply here and I will reopen the issue.**
