### ISSUE TITLE
[BUG] (WingetUI sometimes still installs the package that has just been updated after refreshed)

### ISSUE THREAD

**Issue by RimacC2-EV** [Devolutions/UniGetUI#2206]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

Sometimes WingetUI still installs the package that was just updated after it has been updated and a refresh is performed.
This is reflected in the "real-time output".
The following picture may offer some help.

![屏幕截图 2024-05-10 194802](https://github.com/marticliment/WingetUI/assets/125170682/0d48f487-f475-487c-81ab-269f0f260e8d)

Because the logs are too long for Github to hold, I collected them and created some .txt files.Here are them:

[WingetUI log (1).txt](https://github.com/marticliment/WingetUI/files/15274973/WingetUI.log.1.txt)
[WingetUI log (2) - Package Managers.txt](https://github.com/marticliment/WingetUI/files/15274974/WingetUI.log.2.-.Package.Managers.txt)
[WingetUI log (3).txt](https://github.com/marticliment/WingetUI/files/15274975/WingetUI.log.3.txt)

### Steps to reproduce the issue

Update some software packages (my example is updating "Microsoft Visual C++ 2015-2022 Redistributable", its ID is "Microsoft.VCRedist.2015+.x64")

### WingetUI Log

```text
Because the logs are too long for Github to hold, I collected them and created some .txt files.You can find them in the "Describe your issue" part.
```

### Package Managers Logs

```text
Because the logs are too long for Github to hold, I collected them and created some .txt files.You can find them in the "Describe your issue" part.
```

### Screenshots and videos

https://github.com/marticliment/WingetUI/assets/125170682/fb3d4cde-192f-4f92-b1fc-05af4cb09070

**Comment by SarreqTeryx** [comment]
I'm having a similar (the same?) issue, but with .NET Runtime and Windows Desktop Runtime.  I've updated from 8.0.3 to 8.0.5 of both (normally, as Admin, uninstall then reinstall, and by downloading and running from explorer), but WingetUI keeps reporting the installed version as 8.0.3.
