### ISSUE TITLE
[BUG/ISSUE] Unable to upgrade and/or downgrade WingetUI via WingetUI

### ISSUE THREAD

**Issue by lainverse** [Devolutions/UniGetUI#368]
## Describe the bug
Unable to upgrade WingetUI package because part of the application remains in memory during the upgrade (despite main application closes) and locks-out at least \AppData\Local\Programs\WingetUI\VCRUNTIME140.dll
If upgrade/installation is cancelled existing WingetUI version ends up broken and won't run until re-installed.

Upgrade with `winget upgrade wingetui` and re-installation with `winget install wingetui` works fine when WingetUI is already closed.

## To Reproduce
Steps to reproduce the behaviour:
Attempt to install previous version of WingetUI
or
Attempt to upgrade older one to the latest one.

## Expected behaviour
Application closes, installation finishes successfully and preferably application re-opens after the installation.

## The Log
Ctrl+C from error message window I got (actual application closes, so in-app log is not accessible)
```
[Window Title]
Error

[Main Instruction]
Select action

[Content]
C:\Users\lainverse\AppData\Local\Programs\WingetUI\VCRUNTIME140.dll

An error occurred while trying to replace the existing file:
DeleteFile failed; code 5.
Access is denied.

[Try again] [Skip this file (not recommended)] [Cancel installation]
```

Additionally, if "Cancel installation" is selected installed version of WingetUI shows following error
```
---------------------------
Fatal error detected
---------------------------
Error loading Python DLL 'C:\Users\lainverse\AppData\Local\Programs\WingetUI\python310.dll'.
LoadLibrary: The specified module could not be found.


---------------------------
OK   
---------------------------
```

**Comment by lainverse** [comment]
At the very least upgrade / re-installation of the fixed version should work fine. I don't expect upgrade from not fixed version to fixed one to work smooth, but following updates should work.

I do expect cancelling installation due to an error to roll-back application to a previous state, though, instead of breaking it.

**Comment by ppvnf** [comment]
Possibly related to https://github.com/martinet101/WingetUI/issues/215

**Comment by martinet101** [comment]
This change will be effective for next versions
