### ISSUE TITLE
Bug [?] Update <application name> installation location

### ISSUE THREAD

**Issue by tjsuominen** [Devolutions/UniGetUI#91]
When utilizing WinGetUI and <nametheapp> update function, should WinGetUI respect the installation location to UPDATE it into currently installed location and not to create a new installation copy of the <nametheapp> to somewhere else?

Example, I had GIMP 2.10.30 installed (done months earlier using the GIMP installer) on my Win10 in location C:\Program Files\Tools\GIMP

When I performed the 'Update' with WinGetUI, it 'updated' the app by creating a new installation (copy) of GIMP in C:\Users\<username>\AppData\Local\Programs\GIMP 2 which is NOT the location of the previous version.

How this could be avoided / taken into account (if apps are previously installed without WinGetUI)?

Irritating.

**Comment by tjsuominen** [comment]
Ok, will continue to update GIMP manually then.

Just asking: WingetUI should use the <app> installed location no matter how the the original installation has been performed, right?

So GIMP was just an app behaving badly?

**Comment by martinet101** [comment]
> Just asking: WingetUI should use the installed location no matter how the the original installation has been performed, right?

This is not that WingetUI does, but rather installers should. In my experience with installersd such as Inno, nsis, etc; all of them did that if they were properly configured to do that
